### PR TITLE
Gnome 45 support

### PR DESCRIPTION
**Pull request by romixch**
This should fix https://github.com/CZ-NIC/run-or-raise/issues/60

- Use `const` instead of `var` at some places.
- Move app into extension class as a member variable.
- Export `parseLine` to create Action instead of directly export Action.
- Refactor the preferences dialog. Gnome 45 did not display all the text as the dialog was too wide.

### CODE REVIEW

**Comment by e3rd** [comment]
I've checked the code and it seems amazing, thanks! However, it tells me "This branch cannot be rebased due to conflicts". Would you be so kind and gave a look on it too, please?

**Comment by romixch** [comment]
On my github app on android it says "Ready to merge". But I will have a look at it later this day.

**Comment by romixch** [comment]
Could you tell me how exactly you merge or rebase the pull request. I would like to fix this but I can't reproduce it.

**Comment by e3rd** [comment]
Pretty strange that it tells you it's ok in an app, it shows me this:

image

Normally, this button is green.

**Comment by e3rd** [comment]
Hey, I made it! The problem was – I prefer to rebase so that your commits stay. But as you had a merge commit, the rebasing was not an option. However, I could made the button to squash and merge. That way, your changes are merged, the git tree is not polluted with the merged lines, the only thing, your commits mixed into one. Thanks again for your help, I'll publish this version for Gnome 45 soon.

**Pull request merged**
