### PR TITLE
focus workspace, if window active, switch back to prev window

### PR DESCRIPTION
**Pull request by zba**
Some usefull features, I going to use,
I based on code at extension page on Gnome3, seems you not updated github for a while, and it was refactored for es6 before me.

### CODE REVIEW

**Comment by e3rd** [comment]
It is just the opposite way – GitHub version is the new one and Gnome3 version is the non-updated. Because it is a keystroke to update GitHub but much more work to keep the Gnome3 updated. We've just downgraded from ES6 back: Unfortunately, that was the one reasonable way how to catch the backwards compatibility as asked in #9 . Please, use the current GitHub as the base code.

> focus workspace

It's already working for me. If I am at another workspace and hit the shortcut, both the right workspace and the window get focus. For you it wasn't the case? What OS do you have please? Mine is Ubuntu 17.10.

> if window active, switch back to prev window

This feature is not the one intended in my workflow. Since I have multiple monitors and want to use the system without looking, I often hit the shortcut just to be sure I'm in the right window. If you need that feature, could you please implement that as an option in the configuration so the user can decide what suits them best?

Thanks for your activity!

**Comment by zba** [comment]
focus workspace - I using 18.04 ubuntu, did not worked, take a look at patch, seems you need to move to workspace 1st, before raise window. 

I also have idea to move mouse to center of new focused window, because I have sloopy focus and sometime not fullscreen windows steal it  unexpectedly.


Thanks, for clarification, btw with multidisplay is even better, I setup secondary display as static (not switched workspaces) and switch on primary, so I can use console with ctrl+~ and switch focus back same key, but you are right it should be optional, sadly I have a little experience with gnome-shell extensions, and usually have no idea where to find documentation, do  you know good resources ?

I going to send some pull requests (found that sometime window title is null, which cause search to abort)

**Comment by e3rd** [comment]
> focus workspace

Alright, I just pushed this line to make this work on 18.04.

> move mouse to center

Looking forward to a pull request to have this option configurable! :)

> gnome-shell extensions

I also suffer from lack of documentation. :( And I really hate that I have to log in and out before the change takes place. The method I did this was to cut out information from similar gnome-shell applications, any application of your choice that uses preferences will do.

It seems that gnome-shell uses a Convenience object in `prefs.js` file to preserve user's settings.

```js
const Convenience = Me.imports.convenience;
```

That Convenience can be imported and read from in `extension.js` too.

**Comment by zba** [comment]
You can run alt+f2 r

**Comment by zba** [comment]
I found it in some alt tab source, maybbe original extension, not remember well

**Comment by e3rd** [comment]
> alt+f2, r

Very cool, I'm pretty sure that didn't work few months ago when I was writing the extension. Thanks!

**Pull request closed without merging**
